# Generated by Django 3.2.25 on 2026-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount_gbp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('message', models.TextField(blank=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
