# Generated by Django 3.2.25 on 2026-01-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='session_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.AddField(
            model_name='bookingchild',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bookings.booking'),
        ),
    ]
